# Generated by Django 6.0.2 on 2026-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_patients', models.IntegerField(default=0)),
                ('new_patients', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('completed_appointments', models.IntegerField(default=0)),
                ('emergency_requests', models.IntegerField(default=0)),
                ('average_wait_time', models.FloatField(default=0)),
                ('patient_satisfaction_score', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'hospital_metrics',
                'ordering': ['-date'],
            },
        ),
    ]
