# Generated by Django 6.0.2 on 2026-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('bed', 'Hospital Bed'), ('ventilator', 'Ventilator'), ('icu', 'ICU'), ('equipment', 'Medical Equipment'), ('medicine', 'Medicine Stock')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('total_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_resources',
            },
        ),
    ]
