# Generated by Django 6.0.2 on 2026-02-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('nurses', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('nurse_notified', 'Nurse Notified'), ('nurse_responded', 'Nurse Responded'), ('doctor_escalated', 'Doctor Escalated'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('nurse_notified_at', models.DateTimeField(blank=True, null=True)),
                ('nurse_responded_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='doctors.doctor')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='nurses.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='patients.patient')),
            ],
            options={
                'db_table': 'emergency_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
